Repository photoprism/photoprism, pull requests merged in 2021-01, with the labels that each got.

#824 Remove unused Chart.js dependency
  frontend/package-lock.json
  frontend/package.json
Labels: waiting

#836 Remove use of string-strip-html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/util.js
  frontend/src/common/viewer.js
Labels: done

#833 Add a link to photoprism-mobile in readme
  README.md
Labels: waiting

#839 Remove moment.js from build
  frontend/package-lock.json
  frontend/package.json
  frontend/src/options/options.js
Labels: done

#868 Migrate from deprecated slot syntax
  frontend/src/component/album/clipboard.vue
  frontend/src/component/file/clipboard.vue
  frontend/src/component/label/clipboard.vue
  frontend/src/component/navigation.vue
  frontend/src/component/photo/clipboard.vue
  frontend/src/share/album/clipboard.vue
  frontend/src/share/photo/clipboard.vue
Labels: todo

#867 Migrate templates containing both slot and slot-scope
  frontend/src/component/photo/list.vue
  frontend/src/pages/settings/sync.vue
  frontend/src/share/photo/list.vue
Labels: todo

#854 Update gitignore for static assets
  .gitignore
  assets/static/build/.gitignore
Labels: todo

#863 Remove unused npm packages
  frontend/package-lock.json
  frontend/package.json
Labels: todo

#951 (docs) update README.md
  README.md
Labels: waiting
