Repository photoprism/photoprism, pull requests merged in 2022-09, with the labels that each got.

#2693 Add Sony .HIF file extension
  pkg/fs/file_exts.go
Labels: raw

#2623 Import: Save the original filenames of related files
  internal/photoprism/import_worker.go
  internal/photoprism/import_worker_test.go
Labels: enhancement

#2730 Docker: Switch from gosu to setpriv in entrypoint.sh
  Makefile
  docker/photoprism/armv7/Dockerfile
  docker/photoprism/bookworm/Dockerfile
  docker/photoprism/bullseye/Dockerfile
  docker/photoprism/buster/Dockerfile
  docker/photoprism/impish/Dockerfile
  docker/photoprism/jammy/Dockerfile
  scripts/dist/entrypoint.sh
  scripts/dist/install-go-tools.sh
Labels: enhancement, docker
