Repository photoprism/photoprism, pull requests merged in 2023-07, with the labels that each got.

#3532 Frontend: Show thumbnail in the Labels tab of the edit dialog
  frontend/src/dialog/photo/edit/labels.vue
Labels: enhancement, ux

#1873 XMP: Add support for reading fstop:favorite flag
  internal/meta/data.go
  internal/meta/testdata/fstop-favorite.xmp
  internal/meta/xmp.go
  internal/meta/xmp_document.go
  internal/meta/xmp_test.go
  internal/photoprism/index_mediafile.go
Labels: enhancement, metadata

#3568 Frontend: Allow paste of lat/lng in single operation
  frontend/src/dialog/photo/edit/details.vue
Labels: waiting, enhancement, ux

#2596 Places: Add Cluster View
  frontend/src/component/photo/toolbar.vue
  frontend/src/css/maps.css
  frontend/src/css/navigation.css
  frontend/src/page/photos.vue
  frontend/src/page/places.vue
  internal/form/search_photos.go
  internal/search/photos.go
Labels: enhancement, in-progress, ux, places
