Repository photoprism/photoprism, pull requests merged in 2025-03, with the labels that each got.

#4691 Faces: Improve performance when manual tagging
  internal/api/markers.go
  internal/entity/query/faces.go
  internal/entity/query/faces_test.go
  internal/photoprism/faces_optimize.go
Labels: enhancement, in-progress, performance

#4608 WebDAV: Add depth header to service discovery request for Hetzner compatibility
  internal/service/remote.go
Labels: enhancement, sharing

#4506 CI: Add codespell config and fix typos
  .codespellrc
  docker/demo/traefik.yaml
  internal/api/download_album.go
  internal/api/swagger.json
  internal/api/video.go
  internal/config/config.go
  internal/config/config_db.go
  internal/entity/album_yaml.go
  internal/entity/photo.go
  internal/entity/photo_title_test.go
  internal/entity/photos.go
  internal/entity/search/photos_filter_albums_test.go
  internal/entity/search/photos_filter_filename_test.go
  internal/entity/search/photos_filter_name_test.go
  internal/entity/search/photos_geo_filter_albums_test.go
  internal/entity/string_test.go
  internal/photoprism/backup/albums.go
  internal/photoprism/convert_image.go
  pkg/clean/gps_test.go
  pkg/clean/type_test.go
  pkg/clusters/README.md
  pkg/txt/country.go
  pkg/txt/datetime_year.go
  pkg/txt/is_test.go
  pkg/vector/values.go
  scripts/dist/convert/policy.xml
  setup/docker/cloud/traefik.yaml
Labels: enhancement, ci
