Repository photoprism/photoprism, pull requests merged in 2025-06, with the labels that each got.

#5014 Tests: convert all tests from mocha to vitest
  .gitignore
  Makefile
  frontend/package-lock.json
  frontend/package.json
  frontend/tests/vitest/common/api.test.js
  frontend/tests/vitest/common/can.test.js
  frontend/tests/vitest/common/clipboard.test.js
  frontend/tests/vitest/common/config.test.js
  frontend/tests/vitest/common/form.test.js
  frontend/tests/vitest/common/notify.test.js
  frontend/tests/vitest/common/session.test.js
  frontend/tests/vitest/common/util.test.js
  frontend/tests/vitest/common/view.test.js
  frontend/tests/vitest/component/loading.test.js
  frontend/tests/vitest/component/sidebar/info.test.js
  frontend/tests/vitest/config.js
  frontend/tests/vitest/fixtures.js
  frontend/tests/vitest/model/album.test.js
  frontend/tests/vitest/model/config-options.test.js
  frontend/tests/vitest/model/face.test.js
  frontend/tests/vitest/model/file.test.js
  frontend/tests/vitest/model/folder.test.js
  frontend/tests/vitest/model/label.test.js
  frontend/tests/vitest/model/link.test.js
  frontend/tests/vitest/model/marker.test.js
  frontend/tests/vitest/model/photo.test.js
  frontend/tests/vitest/model/rest.test.js
  frontend/tests/vitest/model/service.test.js
  frontend/tests/vitest/model/settings.test.js
  frontend/tests/vitest/model/subject.test.js
  frontend/tests/vitest/model/thumb.test.js
  frontend/tests/vitest/model/user.test.js
  frontend/tests/vitest/options/options.test.js
  frontend/tests/vitest/setup.js
  frontend/tests/vitest/vue-setup.js
  frontend/vitest.config.js
Labels: frontend, merged, tests

#5042 Backend: Set content-type on metrics endpoints
  internal/api/metrics.go
  internal/api/metrics_test.go
  pkg/media/http/header/content_types.go
Labels: waiting, api

#4999 Albums: Add "Delete Album" action to the album toolbar menu
  frontend/src/component/album/toolbar.vue
Labels: ux

#5068 Setup: Add Cloud-Init configuration for the PhotoPrismPi SD image
  setup/photoprismpi/meta-data
  setup/photoprismpi/network-config
  setup/photoprismpi/user-data
Labels: raspberry-pi, docker, merged

#5074 SQLite: Fix "too many SQL variables" error when flagging pictures as hidden
  internal/entity/query/photo.go
  internal/entity/query/photo_test.go
Labels: bug, database
